name: Weekly Automation

on:
  schedule:
    # 每週六早上 9:00 執行 (UTC+8)
    - cron: "0 1 * * 6"
  workflow_dispatch:
    # 允許手動觸發

jobs:
  weekly-automation:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Configure Git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      - name: Run weekly automation
        run: bash scripts/run-all-steps.sh
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}

      - name: Create summary
        if: always()
        run: |
          echo "## 週一自動化執行結果" >> $GITHUB_STEP_SUMMARY
          echo "- 執行時間: $(date)" >> $GITHUB_STEP_SUMMARY
          echo "- 狀態: ${{ job.status }}" >> $GITHUB_STEP_SUMMARY
